### ISSUE TITLE
Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by jlleblanc** [geotrellis/geotrellis-chatta-demo#14]
I'm unable to get the demo to run. After installing `sbt` and `scala` via Homebrew (on OS X El Capitan) I cloned this project and navigated to the `geotrellis` directory in my terminal window. When I got there, I ran `./sbt run` as the instructions direct. This is the error I encountered as a result:

```
Detected sbt version 0.13.8
Downloading sbt launcher 0.13.8:
  From  http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
    To  ./.lib/0.13.8/sbt-launch.jar
Using /Users/justjoe/.sbt/0.13.8 as sbt dir, -sbt-dir to override.
Error: Invalid or corrupt jarfile ./.lib/0.13.8/sbt-launch.jar
```

**Comment by pomadchin** [comment]
Hey @jlleblanc , i hope you resolved your issues with a local sbt setup; i think the right steps were - manual sbt.jar file removal and re-downloading it. I'll close this issue, but feel free to reopen it again!
