### ISSUE TITLE
load data

### ISSUE THREAD

**Issue by wsf1990** [geotrellis/geotrellis-chatta-demo#17]
dose anybody know how this demo load the data in the data dir?

**Comment by pomadchin** [comment]
@wsf1990 what to you mean by `how`?

There is a short README with a brief description. In short: using the ingest script (that's an example to ingest into Accumulo) you can ingest data into your storage (accumulo / s3 / hadoop / file). In fact is uses [GeotrellisETL](https://github.com/geotrellis/geotrellis/blob/master/docs/spark-etl/spark-etl-intro.md)

**Comment by wsf1990** [comment]
I means how dose this demo know what data in the data dir dose it need when render PNG?

**Comment by pomadchin** [comment]
Demo divided into to parts: 
 * ingest - ingests data in a certain place, indexed, tiled and so on
 * server - it grabs data you ingested (routes depend on layer names)
  * client part - js demo, layer names with default weights are specified [there](https://github.com/geotrellis/geotrellis-chatta-demo/blob/master/static/config.json)

So what do you mean by `know what data in the data dir`?

**Comment by wsf1990** [comment]
where is the ingest part? I cant find it in the src

**Comment by pomadchin** [comment]
Ingest script: https://github.com/geotrellis/geotrellis-chatta-demo/blob/master/geotrellis/ingest.sh
Src: https://github.com/geotrellis/geotrellis-chatta-demo/blob/master/geotrellis/src/main/scala/geotrellis/chatta/ChattaIngest.scala
Src explanations: https://github.com/geotrellis/geotrellis/blob/master/docs/spark-etl/

**Comment by wsf1990** [comment]
I got it in this version.But why cant i find it in the last version?is it the new added? or this is my mistake?

**Comment by pomadchin** [comment]
_This_ version is the _last_ version actually, that's a master branch. Probably you are talking about previous GeoTrellis 0.9.x?

**Comment by wsf1990** [comment]
yes, I clone this demo in the last week,then I can run this Demo.But i cant understand how this demo load the data its need. Last version of this demo have not use spark.

**Comment by wsf1990** [comment]
I got it,Demo load data by the class of RasterSource and Catlog in GeoTrellis 0.9
