### ISSUE TITLE
renderPng

### ISSUE THREAD

**Issue by wsf1990** [geotrellis/geotrellis-chatta-demo#21]
When I run this demo in spark and request the gt/tms,But why can I just get a digit array not a png image?

**Comment by pomadchin** [comment]
Solution was found in a [GeoTrellis gitter channel](https://gitter.im/geotrellis/geotrellis). In short: there was an `import spray.json.DefaultJsonProtocol._` in a global scope, as a consequence `Array[Byte]` was converted to Json representation.

**Comment by lzxue** [comment]
we use geoTrellis too . can add wechat friend , wechat number  qqlzxue
