### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by marfago** [geotrellis/geotrellis-chatta-demo#25]
Following the short guide in the home page of the project to setup a demo with docker gives:

[root@c5b34b71fb1c data]# ./ingest.sh
--class geotrellis.chatta.ChattaIngest --driver-memory=2G target/scala-2.10/GeoTrellis-Tutorial-Project-assembly-0.1-SNAPSHOT.jar   --input file:////data/conf/input.json   --output file:///data/conf/output.json   --backend-pr
ofiles file:///data/conf/backend-profiles.json
Exception in thread "main" java.lang.NoClassDefFoundError: geotrellis/raster/stitch/Stitcher
        at geotrellis.chatta.ChattaIngest$.<clinit>(ChattaIngest.scala))
        at geotrellis.chatta.ChattaIngest.main(ChattaIngest.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.lang.reflect.Method.invoke(Method.java:497)DelegatingMethodAccessorImpl.java:43)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)t$$runMain(SparkSubmit.scala:729)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)0)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381))
Caused bat java.lang.ClassLoader.loadClass(ClassLoader.java:424)titch.Stitcher
        ... 12 moreg.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by marfago** [comment]
Resolved with
./sbt assembly

**Comment by kklt** [comment]
I have some problems about geotrellis-chatta-demo , what is your email?

**Comment by pomadchin** [comment]
Hey @kklt you can use our gitter channel, where we can have a real time talk about problems you have with trying this demo :)

**Comment by pomadchin** [comment]
https://github.com/locationtech/geotrellis#contact-and-support

**Comment by pomadchin** [comment]
@kklt yes, I remember that you you even started your questions :d but suddenly stopped.

**Comment by kklt** [comment]
@pomadchin  I want to run geotrellis-chatta-demo.   my environment is CDH5.5  with spark1.5 .  I  use  SBT    compile package this  demo ,  then  execute ./ingest.sh  but it can run successfully. 
![image](https://cloud.githubusercontent.com/assets/8458160/24320736/100e27c2-1176-11e7-9d92-13d93fb6a1b6.png)  it is  the fault .  how could I  sovle this problem ?  it must use spark2.0？

**Comment by pomadchin** [comment]
Are you sure that you have the latest master branch? Because [this](https://github.com/geotrellis/geotrellis-chatta-demo/blob/master/geotrellis/build.sbt#L32) and [this](https://github.com/geotrellis/geotrellis-chatta-demo/blob/master/geotrellis/project/plugins.sbt#L1) should resolve your problems. 

Btw, we don't maintain Spark 1.x compatibility so here may be issues in your case. And GeoTrellis 1.+ supports scala 2.11 only.

**Comment by kklt** [comment]
@pomadchin  I have create a room in  https://gitter.im/kklt/Lobby#   ,I want to learn from you and  I am a  chinese

**Comment by pomadchin** [comment]
@kklt I appreciate it a lot :) but why can't we use GeoTrellis channel? There may be a lot of other people experiencing similar issues, and our conversation can be useful for them.

**Comment by marfago** [comment]
Hi @pomadchin, I had to rework a little the demo at the time I was working on it, but in the end I was able to fix it and make it working with spark-2.11.

**Comment by pomadchin** [comment]
Yo @marfago great news :+1: , glad that it worked for you!
And currently demo master branch is updated and depends on the latest GeoTrellis.

**Comment by marfago** [comment]
Great news! I will take a look at it. Thank you.

**Comment by kklt** [comment]
@marfago  how  you  run  this  DEMO  successfully?
