### ISSUE TITLE
Ingest-data not avaliable via S3

### ISSUE THREAD

**Issue by blue4world** [geotrellis/geotrellis-chatta-demo#48]
I can not access S3 bucket at s3://geotrellis-chatta-demo/ingest-data.zip
Is bucket set to public read?

**Comment by rossbernet** [comment]
all data for the demo is public:

https://github.com/geotrellis/geotrellis-chatta-demo/tree/master/service/geotrellis/data/arg_wm

**Comment by pomadchin** [comment]
Hm it looks like we don't have them in this repo indeed; try to download them from here: https://github.com/pomadchin/geotrellis-chatta-demo/tree/feature/cassandra-support/geotrellis/data/arg_wm

**Comment by pomadchin** [comment]
Also these objects @rossbernet pointed you to - are itself pointers to tiffs stored in `git lfs`. The solution would be to install `git lfs` on your machine and to run `git lfs fetch --all`.

I'm closing this issue as it looks like a resolved one.
