### ISSUE TITLE
The requested resource could not be found.

### ISSUE THREAD

**Issue by snowmanirl** [geotrellis/geotrellis-chatta-demo#51]
I'm a new to geotrellis and I tried a few days to run the chatta demo using the vagrant or docker,sbt run.Docker run successfully,but in Intellij idea I been using sbt-shell or run main methond to lunch the server,but the browser always shows the message "The requested resource could not be found." I would like to debug this project in idea,is it feasible? and the shell show nothing to me,while when I used https://localhost:8777,the shell shows sth https problem.
 ps:I've ingested the chatta-data by injecting the args in the Ingest method.Could some one give a favor.Plz help!!

**Comment by pomadchin** [comment]
hey @tosen1990! Double check [this setting](https://github.com/geotrellis/geotrellis-chatta-demo/blob/master/service/geotrellis/src/main/resources/application.conf#L3), i'd say even try to provide the absolute path there to the [static dir](https://github.com/geotrellis/geotrellis-chatta-demo/tree/master/service/static). Let me know how it works for you.

**Comment by snowmanirl** [comment]
hey @pomadchin   thank you very much.I spend much time trying every means to fix this according to the dock yam config before you said to me! Now it's working. I spend much time learning geotrellis as a beginner.Feel it's far more harder than I thought before.Cuz the geotrellis document is much few.Can you bro give me some advice to learn geotrellis?I'll be grateful to it.

**Comment by pomadchin** [comment]
thx for your feedback @tosen1990 
we have a couple of demos and our gitter channel where you can chat with use in real time
and any suggestions about what you want to see to be covered in docs is very much appreciated!
