### ISSUE TITLE
Typo in plugins.sbt

### ISSUE THREAD

**Issue by arsgeografica** [geotrellis/geotrellis-chatta-demo#8]
[Line 6](https://github.com/geotrellis/geotrellis-chatta-demo/blob/master/geotrellis/project/plugins.sbt#L6) should end in ```")```, not in ```)"```

**Comment by lossyrob** [comment]
Whoa, looks like an emacs transpose typo. Fixed, thanks!

**Comment by arsgeografica** [comment]
So you say it wouldn't have happened with Vim? ;)

**Comment by lossyrob** [comment]
:hurtrealbad: lol
