### ISSUE TITLE
how to run this demo

### ISSUE THREAD

**Issue by qweqweq** [geotrellis/geotrellis-chatta-demo#9]
please help me ,when i try to run this demo ,i got a problem with that:
[root@master geotrellis]# ./sbt run
bash: ./sbt: Permission denied.

i use the ubuntu14.04 os .i install scala,jdk,sbt,and maven.
Can anybody who konws the details about how to run this demo,please tell me ,thank you very much!

**Comment by qweqweq** [comment]
I know how to run it.if you use scala2.11.x will got some waring  and error such as :
[warn] com.azavea.geotrellis#geotrellis_2.11;0.9.2: not found
[warn] com.azavea.geotrellis#geotrellis-services_2.11;0.9.2: not found

but when i use the scala2.10 it works!

**Comment by qweqweq** [comment]
![image](https://cloud.githubusercontent.com/assets/10056390/8205947/c3d1bbd6-1527-11e5-8cfd-3ec983661b08.png)

**Comment by wsf1990** [comment]
hi,dose you know how to deploy it to hostname ,like http://name1:8777?

**Comment by wsf1990** [comment]
thanks,I got it
./sbt run -Dgeotrellis.hostname=your.hostname

**Comment by ZhengDigua** [comment]
how can you load such picture when you draw a polygon,I have try a day,but it doesn't work.Please share with me.Very thank with you!

**Comment by qweqweq** [comment]
@ZhengDigua  这个隔了好久了啊，emmm，你按照官方文档来配置就可以了啊，注意版本。

**Comment by ZhengDigua** [comment]
嗯嗯~谢谢您！




------------------ 原始邮件 ------------------
发件人: "yuho";<notifications@github.com>;
发送时间: 2018年1月29日(星期一) 晚上9:42
收件人: "geotrellis/geotrellis-chatta-demo"<geotrellis-chatta-demo@noreply.github.com>;
抄送: "郑欣彤"<986439461@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [geotrellis/geotrellis-chatta-demo] how to run this demo (#9)




@ZhengDigua  这个隔了好久了啊，emmm，你按照官方文档来配置就可以了啊，注意版本。

**Comment by pomadchin** [comment]
I believe we can discuss it in #46 and this issue can be closed? @qweqweq
